
import React from "react";
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import styles from "@component/dashboard/editPost/editPostStyle.module.css";
import GeneralContextProvider from "@/components/context/GeneralContextProvider";
import PostContextProvider, { PostContext } from "@/components/context/PostContextProvider";




const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Edit Post',
    description: 'Generated by create next app',
}

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <main className={styles.editPostLayout}>
            <GeneralContextProvider>
                <PostContextProvider>
                    {children}
                </PostContextProvider>
            </GeneralContextProvider>


        </main>
    )
}