
import React from "react";
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';




const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create post',
    description: 'Generated by create next app',
}

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <main className="lg:container mx-auto ">

            {children}


        </main>
    )
}