import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css';
import "@pages/globalsTwo.css";
import Nav from "@component/nav/Nav";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-slate-600 relative lg:container mx-auto w-full" style={{ position: "relative" }} >
        <Nav />
        {children}

      </body>
    </html>
  )
}
