import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import './globals.css';
import "@pages/globalsTwo.css";
import Nav from "@component/nav/Nav";
import Providers from "./providers";
import GeneralContextProvider from '@/components/context/GeneralContextProvider';
import BlogContextProvider from "@context/BlogContextProvider";
import PostContextProvider from "@context/PostContextProvider";
import MainHeader from "./MainHeader";
import Footer from "@component/footer/Footer";
import ToasterContext from "@context/ToasterContext";



const inter = Inter({ subsets: ['latin'] });

const baseUrl = new URL("https://www.ablogroom.com");
const local = new URL("http://localhost:3000");

export const metadata: Metadata = {
  metadataBase: process.env.NODE_ENV === "production" ? baseUrl : local,
  title: {
    default: "Blog Room",
    template: `%s | Blog Room`,

  },
  description: 'Generated by www.masterconnect.ca,Free Blog Creation for you. It provides templates that the user can use to become an effective blogger. The Blog Room has all the effective tools for the blogger to fine-tune their skills in blogging. ',
  verification: {
    google: 'S88O7lTinqgyYLB8h1x2fOusiDQY9V68xuDpUZevLQY',
    yandex: 'yandex',
    yahoo: 'yahoo',
    other: {
      name: ['masterconnect919@gmail.com', 'https://www.masterconnect.ca/contact'],
    },
  },

  generator: "Next.js",
  applicationName: "apitest",
  referrer: "strict-origin-when-cross-origin",
  keywords: ["The Blog Room, Free to use", "blogs for you", "web info", "free blogs & posts", " The World is Your Oyster", " Create Your Own Blog", "Gary's Blogs"],
  authors: [{ name: "Gary Wallace", url: "https://www.ablogroom.com" }, { name: "Gary Wallace", url: "https://www.masterconnect.ca" }],
  // colorScheme:"light",
  creator: "Gary Wallace",
  publisher: "Gary Wallace",
  formatDetection: {
    email: true,
    address: false,
    telephone: true
  },
  openGraph: {
    title: "a Blog Room",
    description: 'Generated by www.masterconnect.ca, blogs for you',
    url: "https://www.ablogroom.com",
    siteName: "a Blog Room",
    images: [
      {
        url: "/images/gb_logo.png",
        width: 600,
        height: 800
      },

    ],
    locale: "en-CA",
    type: "website"

  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
    },
  },
  icons: {
    icon: '/icon.png',
    shortcut: '/icon.png',
    apple: '/icon.png',
    other: {
      rel: 'apple-touch-icon-precomposed',
      url: '/icon.png',
    },

  },
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
  },

  appleWebApp: {
    title: 'Apple Web App',
    statusBarStyle: 'black-translucent',
    startupImage: [
      '/assets/startup/apple-touch-startup-image-768x1025.png',
      {
        url: '/assets/startup/apple-touch-startup-image-1536x2051.png',
        media: '(device-width: 768px) and (device-height: 1024px)',
      },
    ],
  },


}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className="bg-slate-200 rootBody"  >
        <Providers>
          <GeneralContextProvider>
            <BlogContextProvider>
              <PostContextProvider>
                <ToasterContext />
                <MainHeader />
                {children}
                <Footer />
              </PostContextProvider>
            </BlogContextProvider>
          </GeneralContextProvider>
        </Providers>
      </body>
    </html>
  )
}
