
import React from "react";
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import styles from "@component/dashboard/dashboard.module.css";
import GeneralContextProvider, { GeneralContext } from "@/components/context/GeneralContextProvider";
import BlogContextProvider from "@/components/context/BlogContextProvider";




const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app',
    referrer: "strict-origin",
    robots: {
        index: false,
        follow: false,
        nocache: false,

    },
}

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <main className={`${styles.dashboardLayout} bg-slate-900`}>
            <GeneralContextProvider>
                <BlogContextProvider>
                    {children}
                </BlogContextProvider>
            </GeneralContextProvider>


        </main>
    )
}