
import React from "react";
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import styles from "@component/blog/blog.module.css";
import GeneralContextProvider from "@/components/context/GeneralContextProvider";

export const metadata: Metadata = {
    title: "Contact Us",
    description: " ablogroom.com contact page",
    keywords: ["ablogroom's contact page", "free blogs and comments"],
    openGraph: {
        title: "a Blog Room",
        description: 'Generated by www.masterconnect.ca, blogs for you',
        url: "https://www.ablogroom.com/contactUs",
        siteName: "a Blog Room",
        images: [
            {
                url: "/images/happyFamily.png",
                width: 600,
                height: 800
            },

        ],
        locale: "en-CA",
        type: "website"

    },
}

const inter = Inter({ subsets: ['latin'] })

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <GeneralContextProvider>
            {children}
        </GeneralContextProvider>
    )
}